### PR TITLE
Update issue templates

### PR DESCRIPTION
**Pull request by skanwal**

### CODE REVIEW

**Comment by skanwal** [comment]
@lindsmith - I have used GH resources to add bug report and feature request templates. 
We can also make changes to it, if you'd like to suggest anything.

I'll add a PR template later as well.

**Review by lindsmith — APPROVED** [review]
Thanks @skanwal - this is excellent and I'm happy to approve as is. Before merging, I'll flag to the rest of the group to review and let us know if they have any comments.

**Comment by skanwal** [comment]
@lindsmith - okay, I'll hold-on merging it.
I have merged in the other PR https://github.com/ga4gh/quality-control-wgs/pull/6 (sorry didn't realise you wanted to flag these to rest of the group). Happy to open up another PR if anyone has change request.

**Comment by lindsmith** [comment]
@skanwal - no problem at all with merging, in fact, I'll merge this one now. As you pointed out we can just open a new PR if needed!

**Pull request merged**
